changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      label: 'bug'
    - title: '📚 Documentation'
      label: 'documentation'
    - title: '🛠️ Refactoring'
      label: 'refactor'
    - title: '🚀 Performance'
      label: 'performance'
    - title: '🎨 GUI'
      label: 'gui'
    - title: '💻 Backend'
      label: 'backend'
  exclude:
    labels:
      - 'skip-changelog'
